name: ci pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: set up node jobs
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install dependencies
        run: npm install

      - name: run tests
        run: npm run test
